apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdate
  labels:
    app: nginxdate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxdate
  template:
    metadata:
      labels:
        app: nginxdate
    spec:
      containers:
      - name: nginxdate
        image: eranif/nginxdate
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginxdate
spec:
  selector:
    app: nginxdate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginxdate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nginxdate
          servicePort: 80